INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('01','Ain','84','Auvergne-Rhône-Alpes');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('02','Aisne','32','Hauts-de-France');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('03','Allier','84','Auvergne-Rhône-Alpes');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('04','Alpes-de-Haute-Provence','93','Provence-Alpes-Côte d\'Azur');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('05','Hautes-Alpes','93','Provence-Alpes-Côte d\'Azur');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('06','Alpes-Maritimes','93','Provence-Alpes-Côte d\'Azur');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('07','Ardèche','84','Auvergne-Rhône-Alpes');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('08','Ardennes','44','Grand-Est');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('09','Ariège','76','Occitanie');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('10','Aube','44','Grand-Est');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('11','Aude','76','Occitanie');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('12','Aveyron','76','Occitanie');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('13','Bouches-du-Rhône','93','Provence-Alpes-Côte d\'Azur');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('14','Calvados','28','Normandie');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('15','Cantal','84','Auvergne-Rhône-Alpes');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('16','Charente','75','Nouvelle-Aquitaine');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('17','Charente-Maritime','75','Nouvelle-Aquitaine');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('18','Cher','24','Centre-Val de Loire');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('19','Corrèze','75','Nouvelle-Aquitaine');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('21','Côte-d\'or','27','Bourgogne-Franche-Comté');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('22','Côtes-d\'armor','53','Bretagne');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('23','Creuse','75','Nouvelle-Aquitaine');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('24','Dordogne','75','Nouvelle-Aquitaine');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('25','Doubs','27','Bourgogne-Franche-Comté');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('26','Drôme','84','Auvergne-Rhône-Alpes');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('27','Eure','28','Normandie');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('28','Eure-et-Loir','24','Centre-Val de Loire');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('29','Finistère','53','Bretagne');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('2a','Corse-du-Sud','94','Corse');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('2b','Haute-Corse','94','Corse');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('30','Gard','76','Occitanie');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('31','Haute-Garonne','76','Occitanie');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('32','Gers','76','Occitanie');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('33','Gironde','75','Nouvelle-Aquitaine');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('34','Hérault','76','Occitanie');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('35','Ille-et-Vilaine','53','Bretagne');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('36','Indre','24','Centre-Val de Loire');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('37','Indre-et-Loire','24','Centre-Val de Loire');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('38','Isère','84','Auvergne-Rhône-Alpes');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('39','Jura','27','Bourgogne-Franche-Comté');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('40','Landes','75','Nouvelle-Aquitaine');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('41','Loir-et-Cher','24','Centre-Val de Loire');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('42','Loire','84','Auvergne-Rhône-Alpes');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('43','Haute-Loire','84','Auvergne-Rhône-Alpes');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('44','Loire-Atlantique','52','Pays de la Loire');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('45','Loiret','24','Centre-Val de Loire');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('46','Lot','76','Occitanie');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('47','Lot-et-Garonne','75','Nouvelle-Aquitaine');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('48','Lozère','76','Occitanie');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('49','Maine-et-Loire','52','Pays de la Loire');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('50','Manche','28','Normandie');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('51','Marne','44','Grand-Est');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('52','Haute-Marne','44','Grand-Est');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('53','Mayenne','52','Pays de la Loire');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('54','Meurthe-et-Moselle','44','Grand-Est');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('55','Meuse','44','Grand-Est');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('56','Morbihan','53','Bretagne');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('57','Moselle','44','Grand-Est');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('58','Nièvre','27','Bourgogne-Franche-Comté');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('59','Nord','32','Hauts-de-France');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('60','Oise','32','Hauts-de-France');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('61','Orne','28','Normandie');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('62','Pas-de-Calais','32','Hauts-de-France');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('63','Puy-de-Dôme','84','Auvergne-Rhône-Alpes');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('64','Pyrénées-Atlantiques','75','Nouvelle-Aquitaine');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('65','Hautes-Pyrénées','76','Occitanie');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('66','Pyrénées-Orientales','76','Occitanie');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('67','Bas-Rhin','44','Grand-Est');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('68','Haut-Rhin','44','Grand-Est');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('69','Rhône','84','Auvergne-Rhône-Alpes');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('70','Haute-Saône','27','Bourgogne-Franche-Comté');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('71','Saône-et-Loire','27','Bourgogne-Franche-Comté');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('72','Sarthe','52','Pays de la Loire');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('73','Savoie','84','Auvergne-Rhône-Alpes');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('74','Haute-Savoie','84','Auvergne-Rhône-Alpes');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('75','Paris','11','Ile-de-France');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('76','Seine-Maritime','28','Normandie');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('77','Seine-et-Marne','11','Ile-de-France');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('78','Yvelines','11','Ile-de-France');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('79','Deux-Sèvres','75','Nouvelle-Aquitaine');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('80','Somme','32','Hauts-de-France');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('81','Tarn','76','Occitanie');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('82','Tarn-et-Garonne','76','Occitanie');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('83','Var','93','Provence-Alpes-Côte d\'Azur');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('84','Vaucluse','93','Provence-Alpes-Côte d\'Azur');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('85','Vendée','52','Pays de la Loire');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('86','Vienne','75','Nouvelle-Aquitaine');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('87','Haute-Vienne','75','Nouvelle-Aquitaine');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('88','Vosges','44','Grand-Est');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('89','Yonne','27','Bourgogne-Franche-Comté');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('90','Territoire de Belfort','27','Bourgogne-Franche-Comté');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('91','Essonne','11','Ile-de-France');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('92','Hauts-de-Seine','11','Ile-de-France');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('93','Seine-Saint-Denis','11','Ile-de-France');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('94','Val-de-Marne','11','Ile-de-France');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('95','Val-d\'oise','11','Ile-de-France');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('971','Guadeloupe','01','Guadeloupe');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('972','Martinique','02','Martinique');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('973','Guyane','03','Guyane');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('974','La Réunion','04','La Réunion');
INSERT INTO `department` (`number`,`name`,`regionCode`,`region`) VALUES ('976','Mayotte','06','Mayotte');